var tagText = {
    'x00020000':'Number of bytes following this File Meta Element (end of the Value field) up to and including the last File Meta Element of the Group 2 File Meta Information.',
    'x00020001':'This is a two byte field where each bit identifies a version of this File Meta Information header. In version 1 the first byte value is 00H and the second value byte value is 01H.',
    'x00020002':'Uniquely identifies the SOP Class associated with the Data Set.',
    'x00020003':'Uniquely identifies the SOP Instance associated with the Data Set placed in the file and following the File Meta Information.',
    'x00020010':'Uniquely identifies the Transfer Syntax used to encode the following Data Set. This Transfer Syntax does not apply to the File Meta Information.',
    'x00020012':'Uniquely identifies the implementation that wrote this file and its content. It provides an unambiguous identification of the type of implementation that last wrote the file in the event of interchange problems.',
    'x00020013':'Identifies a version for an Implementation Class UID (0002,0012) using up to 16 characters of the repertoire identified in Section 8.5 of DICOM Standard.',
    'x00020016':'The DICOM Application Entity (AE) Title of the AE that wrote this file\'s content (or last updated it). If used, it allows the tracing of the source of errors in the event of media interchange problems.',
    'x00080005':'Character Set that expands or replaces the Basic Graphic Set. Required if an expanded or replacement character set is used.',
    'x00080008':'Image identification characteristics.',
    'x00080016':'Uniquely identifies the SOP Class.',
    'x00080018':'Uniquely identifies the SOP Instance.',
    'x00080020':'Date the Study started.',
    'x00080021':'Date the Series started.',
    'x00080022':'The date the acquisition of data that resulted in this image started.',
    'x00080023':'The date the image pixel data creation started. Required if image is part of a Series in which the images are temporally related. May be present otherwise.',
    'x00080030':'Time the Study started.',
    'x00080031':'Time the Series started.',
    'x00080032':'The time the acquisition of data that resulted in this image started',
    'x00080033':'The time the image pixel data creation started. Required if image is part of a Series in which the images are temporally related. May be present otherwise.',
    'x00080050':'A RIS generated number that identifies the order for the Study.',
    'x00080060':'Type of equipment that originally acquired the data used to create the images in this Series.',
    'x00080070':'Manufacturer of the equipment that contributed to the composite instance.',
    'x00080080':'Institution where the equipment that contributed to the composite instance is located.',
    'x00080081':'Address of the institution where the equipment that contributed to the composite instance is located.',
    'x00080090':'Patient\'s primary referring physician for this Visit',
    'x00081010':'User defined name identifying the machine that contributed to the composite instance.',
    'x00081030':'Institution-generated description or classification of the Study (component) performed.',
    'x0008103E':'User provided description of the Series.',
    'x00081070':'Name(s) of the operator(s) supporting the Series.',
    'x00081090':'Manufacturer\'s model name of the equipment that contributed to the composite instance.',
    'x00081140':'Other images significantly related to this image (e.g., post-localizer CT image or Mammographic biopsy or partial view images). One or more Items are permitted in this Sequence.',
    'x00081150':'Uniquely identifies the referenced SOP Class.',
    'x00081155':'Uniquely identifies the referenced SOP Instance.',
    'x00082111':'A text description of how this image was derived.',
    'x00089215':'A coded description of how this image was derived. One or more Items are permitted in this Sequence. More than one Item indicates that successive derivation steps have been applied.',
    'x00080100':'The identifier of the Coded Entry. Shall be present if the code value length is 16 characters or less, and the code value is not a URN or URL.',
    'x00080102':'The identifier of the coding scheme in which the Coded Entry is defined. Shall be present if Code Value (0008,0100) or Long Code Value (0008,0119) is present. May be present otherwise.',
    'x00080104':'Text that conveys the meaning of the Coded Entry.',
    'x00100010':'Patient\'s full name.',
    'x00100020':'Primary identifier for the patient.',
    'x00100030':'Date of birth of the named Patient.',
    'x00100040':'Sex of the named Patient. Enumerated Values: M - male,  F - female,  O - other.',
    'x00101010':'Age of the Patient.',
    'x00180015':'Text description of the part of the body examined. See Annex L “Correspondence of Anatomic Region Codes and Body Part Examined Defined Terms” in PS3.16 at DICOM Standard for Defined Terms',
    'x00180050':'Nominal reconstructed slice thickness, in mm.',
    'x00180060':'Peak kilo voltage output of the X-Ray generator used.',
    'x00181000':'Manufacturer\'s serial number of the equipment that contributed to the composite instance.',
    'x00181020':'Manufacturer\'s designation of the software version of the equipment that contributed to the composite instance.',
    'x00181030':'User-defined description of the conditions under which the Series was performed.',
    'x00181110':'Distance in mm from source to detector center.',
    'x00181111':'Distance in mm from source to the table, support or bucky side that is closest to the Imaging Subject, as measured along the central ray of the X-Ray beam.',
    'x00181120':'Nominal angle of tilt in degrees of the scanning gantry. Not intended for mathematical computations.',
    'x00181130':'The distance in mm of the top of the patient table to the center of rotation; below the center is positive.',
    'x00181140':'Direction of rotation of the source when relevant, about nearest principal axis of equipment. Enumerated Values: CW - clockwise, CC - counter clockwise.',
    'x00181160':'Label for the type of filter inserted into the x-ray beam.',
    'x00181170':'Power in kW to the x-ray generator.',
    'x00181190':'Size of the focal spot in mm. For devices with variable focal spot or multiple focal spots, small dimension followed by large dimension.',
    'x00181200':'Date when the image acquisition device calibration was last changed in any way. Multiple entries may be used for additional calibrations at other times.',
    'x00181201':'Time when the image acquisition device calibration was last changed in any way. Multiple entries may be used.',
    'x00181210':'A label describing the convolution kernel or algorithm used to reconstruct the data.',
    'x00185100':'Patient position descriptor relative to the equipment. Required for images where Patient Orientation Code Sequence (0054,0410) is not present and whose SOP Class is one of the following: CT ("1.2.840.10008.5.1.4.1.1.2") or MR ("1.2.840.10008.5.1.4.1.1.4") or Enhanced CT ("1.2.840.10008.5.1.4.1.1.2.1") or Enhanced MR Image ("1.2.840.10008.5.1.4.1.1.4.1") or Enhanced Color MR Image ("1.2.840.10008.5.1.4.1.1.4.3") or MR Spectroscopy ("1.2.840.10008.5.1.4.1.1.4.2") Storage SOP Classes. May be present for other SOP Classes if Patient Orientation Code Sequence (0054,0410) is not present.',
    'x0020000D':'Unique identifier for the Study. Required if Type of Instances (0040,E020) is DICOM',
    'x0020000E':'Unique identifier for the Series that is part of the Study identified in Study Instance UID (0020,000D), if present, and contains the referenced object instance(s). Required if Type of Instances (0040,E020) is DICOM',
    'x00200010':'User or equipment generated Study identifier.',
    'x00200011':'A number that identifies this Series.',
    'x00200012':'A number identifying the single continuous gathering of data over a period of time that resulted in this image.',
    'x00200013':'A number that identifies this Composite object instance.',
    'x00200032':'The x, y, and z coordinates of the upper left hand corner (center of the first voxel transmitted) of the image, in mm.',
    'x00200037':'The direction cosines of the first row and the first column with respect to the patient.',
    'x00200052':'Uniquely identifies the Frame of Reference for a Series.',
    'x00201040':'Part of the imaging target used as a reference.',
    'x00204000':'User-defined comments about the image.',
    'x00280002':'Number of samples (planes) in this image.',
    'x00280004':'Specifies the intended interpretation of the pixel data.',
    'x00280006':'Indicates whether the pixel data are encoded color-by-plane or color-by-pixel. Required if Samples per Pixel (0028,0002) has a value greater than 1.',
    'x00280008':'Number of frames in a Multi-frame Image.',
    'x00280010':'Number of rows in the image.',
    'x00280011':'Number of columns in the image.',
    'x00280030':'Physical distance in the patient between the center of each pixel, specified by a numeric pair - adjacent row spacing (delimiter) adjacent column spacing in mm.',
    'x00280100':'Number of bits allocated for each pixel sample. Each sample shall have the same number of bits allocated. Bits Allocated (0028,0100) shall be either 1, or a multiple of 8.',
    'x00280101':'Number of bits stored for each pixel sample. Each sample shall have the same number of bits stored.',
    'x00280102':'Most significant bit for pixel sample data. Each sample shall have the same high bit. High Bit (0028,0102) shall be one less than Bits Stored (0028,0101).',
    'x00280103':'Data representation of the pixel samples. Each sample shall have the same pixel representation. Enumerated Values: 0000H - unsigned integer ,0001H - 2\'s complement',
    'x00281050':'Window Center for display. Required if VOI LUT Sequence (0028,3010) is not present. May be present otherwise.',
    'x00281051':'Window Width for display. Required if Window Center (0028,1050) is present.',
    'x00281052':'The value b in relationship between stored values (SV) and the output units specified in Rescale Type (0028,1054). Output units = m*SV + b. Required if Modality LUT Sequence (0028,3000) is not present. Shall not be present otherwise.',
    'x00281053':'m in the equation specified by Rescale Intercept (0028,1052). Required if Rescale Intercept is present.',
    'x00281054':'Specifies the output units of Rescale Slope (0028,1053) and Rescale Intercept (0028,1052). Required if Rescale Intercept is present.',
    'x00281055':'Free form explanation of the meaning of the Window Center and Width. Multiple values correspond to multiple Window Center and Width values.',
    'x00282110':'Specifies whether an Image has undergone lossy compression (at a point in its lifetime). Enumerated Values: 00 - Image has NOT been subjected to lossy compression. 01 - Image has been subjected to lossy compression. Once this value has been set to 01 it shall not be reset.'
};